/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  siteUrl: string;
  favicon?: CustomImage;
  keywords?: Array<string>;
  defaultOgImage?: CustomImage;
  organization?: {
    name: string;
    logo?: CustomImage;
    address?: string;
    phone?: string;
    email?: string;
  };
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    linkedin?: string;
    twitter?: string;
  };
};

export type CustomImage = {
  _type: "customImage";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Club = {
  _id: string;
  _type: "club";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  partner?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "partner";
  };
  image?: CustomImage;
  title: string;
  date: string;
  shortDescription: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
  } & CustomImage | {
    _key: string;
  } & ImageGrid | {
    _key: string;
  } & VideoEmbed>;
  slug: Slug;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  keywords?: Array<string>;
  openGraphImage?: CustomImage;
  openGraphTitle?: string;
  openGraphDescription?: string;
  noIndex?: boolean;
  canonicalUrl?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type GalleryFolder = {
  _id: string;
  _type: "galleryFolder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  coverImage: CustomImage;
  slug: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Quote = {
  _id: string;
  _type: "quote";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text: string;
  author: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  partner?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "partner";
  };
  image?: CustomImage;
  title: string;
  date: string;
  shortDescription: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
  } & CustomImage | {
    _key: string;
  } & ImageGrid | {
    _key: string;
  } & VideoEmbed>;
  slug: Slug;
  seo?: Seo;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  partnerImage: CustomImage;
  slug: Slug;
  seo?: Seo;
};

export type PersonnelName = {
  _type: "personnelName";
  name: string;
  description: string;
};

export type Personnel = {
  _type: "personnel";
  firstImage: CustomImage;
  secondImage: CustomImage;
  names?: Array<{
    _key: string;
  } & PersonnelName>;
};

export type VideoEmbed = {
  _type: "videoEmbed";
  url: string;
  caption?: string;
};

export type ImageGrid = {
  _type: "imageGrid";
  images: Array<{
    _key: string;
  } & CustomImage>;
  layout: "2-columns" | "3-columns" | "4-columns" | "masonry";
  gap?: "small" | "medium" | "large";
};

export type CustomFile = {
  _type: "customFile";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
  };
  media?: unknown;
  fileName: string;
};

export type ActionButton = {
  _type: "actionButton";
  text: string;
  href: string;
};

export type StructureInstitutionPage = {
  _id: string;
  _type: "structureInstitutionPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  filesToDownload?: Array<{
    _key: string;
  } & CustomFile>;
  seo?: Seo;
};

export type StructureSchoolPage = {
  _id: string;
  _type: "structureSchoolPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  personnelImages?: Array<{
    _key: string;
  } & Personnel>;
  filesToDownload?: Array<{
    _key: string;
  } & CustomFile>;
  seo?: Seo;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SiteSettings | CustomImage | Club | Seo | Slug | GalleryFolder | SanityImageCrop | SanityImageHotspot | Quote | Post | Partner | PersonnelName | Personnel | VideoEmbed | ImageGrid | CustomFile | ActionButton | StructureInstitutionPage | StructureSchoolPage | MediaTag | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/api/clubsPage/fetchClub/query.ts
// Variable: getClubBySlugQuery
// Query: *[_type == "club" && slug.current == $slug][0] {  title,  description,  partner->{    partnerImage  },  image,  _createdAt,  "slug": slug.current,  seo}
export type GetClubBySlugQueryResult = {
  title: string;
  description: Array<{
    _key: string;
  } & CustomImage | {
    _key: string;
  } & ImageGrid | {
    _key: string;
  } & VideoEmbed | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  partner: {
    partnerImage: CustomImage;
  } | null;
  image: CustomImage | null;
  _createdAt: string;
  slug: string;
  seo: Seo | null;
} | null;

// Source: ./src/api/clubsPage/fetchClubSlugs/query.ts
// Variable: getClubSlugsQuery
// Query: *[_type == "club"] {  "slug": slug.current,}
export type GetClubSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: ./src/api/clubsPage/fetchClubs/query.ts
// Variable: getClubsQuery
// Query: *[_type == "club"] | order(date desc) {  title,  shortDescription,  partner->{    partnerImage,    _id  },  image,  date,  "slug": slug.current,}
export type GetClubsQueryResult = Array<{
  title: string;
  shortDescription: string;
  partner: {
    partnerImage: CustomImage;
    _id: string;
  } | null;
  image: CustomImage | null;
  date: string;
  slug: string;
}>;

// Source: ./src/api/clubsPage/fetchPartners/query.ts
// Variable: getClubsPartnersReferenceDataQuery
// Query: *[_type == "partner"] {  _id,  name}
export type GetClubsPartnersReferenceDataQueryResult = Array<{
  _id: string;
  name: string;
}>;

// Source: ./src/api/fetchSiteSettings/query.ts
// Variable: getSiteSettingsQuery
// Query: *[_type == "siteSettings"]{  title,  siteUrl,  description,  keywords,  defaultOgImage,  organization,  socialMedia}
export type GetSiteSettingsQueryResult = Array<{
  title: string;
  siteUrl: string;
  description: string;
  keywords: Array<string> | null;
  defaultOgImage: CustomImage | null;
  organization: {
    name: string;
    logo?: CustomImage;
    address?: string;
    phone?: string;
    email?: string;
  } | null;
  socialMedia: {
    facebook?: string;
    instagram?: string;
    linkedin?: string;
    twitter?: string;
  } | null;
}>;

// Source: ./src/api/galleryPage/fetchGalleries/query.ts
// Variable: getGalleriesQuery
// Query: *[_type == "galleryFolder"] {  _id,  name,  "slug": slug.current,  coverImage,  "latestImages": images | order(_key desc) [0...3]}
export type GetGalleriesQueryResult = Array<{
  _id: string;
  name: string;
  slug: string;
  coverImage: CustomImage;
  latestImages: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
}>;

// Source: ./src/api/galleryPage/fetchGalleryBySlug/query.ts
// Variable: getGalleryBySlugQuery
// Query: *[_type == "galleryFolder" && slug.current == $slug][0] {  name,  "slug": slug.current,  coverImage,  images[],  seo}
export type GetGalleryBySlugQueryResult = {
  name: string;
  slug: string;
  coverImage: CustomImage;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  seo: Seo | null;
} | null;

// Source: ./src/api/homePage/fetchHomeSections/query.ts
// Variable: getHomeSectionsQuery
// Query: *[_type == "examplePage"]{title,sections,seo}
export type GetHomeSectionsQueryResult = Array<never>;

// Source: ./src/api/homePage/fetchLastThreeProjects/query.ts
// Variable: getLastThreeProjectsQuery
// Query: *[_type == "post"] | order(date desc)[0...3] {  _id,  title,  shortDescription,  image,  date,  "slug": slug.current,  partner->{    name,    partnerImage  }}
export type GetLastThreeProjectsQueryResult = Array<{
  _id: string;
  title: string;
  shortDescription: string;
  image: CustomImage | null;
  date: string;
  slug: string;
  partner: {
    name: string;
    partnerImage: CustomImage;
  } | null;
}>;

// Source: ./src/api/homePage/fetchPartners/query.ts
// Variable: getPartnersQuery
// Query: *[_type == "partner"] {  partnerImage}
export type GetPartnersQueryResult = Array<{
  partnerImage: CustomImage;
}>;

// Source: ./src/api/projectsPage/fetchPartners/query.ts
// Variable: getPartnersReferenceDataQuery
// Query: *[_type == "partner"] {  _id,  name}
export type GetPartnersReferenceDataQueryResult = Array<{
  _id: string;
  name: string;
}>;

// Source: ./src/api/projectsPage/fetchProject/query.ts
// Variable: getProjectQuery
// Query: *[_type == "post" && slug.current == $slug][0] {  title,  description,  image,  partner->{    partnerImage  },  _createdAt,  "slug": slug.current,  seo}
export type GetProjectQueryResult = {
  title: string;
  description: Array<{
    _key: string;
  } & CustomImage | {
    _key: string;
  } & ImageGrid | {
    _key: string;
  } & VideoEmbed | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: CustomImage | null;
  partner: {
    partnerImage: CustomImage;
  } | null;
  _createdAt: string;
  slug: string;
  seo: Seo | null;
} | null;

// Source: ./src/api/projectsPage/fetchProjectSlugs/query.ts
// Variable: getProjectSlugsQuery
// Query: *[_type == "post"] {  "slug": slug.current,}
export type GetProjectSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: ./src/api/projectsPage/fetchProjects/query.ts
// Variable: getProjectsQuery
// Query: *[_type == "post"] | order(date desc) {  title,  shortDescription,  image,  partner->{    partnerImage,    _id  },  date,  "slug": slug.current,}
export type GetProjectsQueryResult = Array<{
  title: string;
  shortDescription: string;
  image: CustomImage | null;
  partner: {
    partnerImage: CustomImage;
    _id: string;
  } | null;
  date: string;
  slug: string;
}>;

// Source: ./src/api/structurePage/fetchFilesToDownload/query.ts
// Variable: getFilesToDownloadQuery
// Query: *[_type == "structureSchoolPage"] {  filesToDownload[] {    fileName,    "downloadUrl": asset->url  }}
export type GetFilesToDownloadQueryResult = Array<{
  filesToDownload: Array<{
    fileName: string;
    downloadUrl: string | null;
  }> | null;
}>;

// Source: ./src/api/structurePage/fetchPersonnelImages/query.ts
// Variable: getPersonnelImagesQuery
// Query: *[_type == "structureSchoolPage"] {  personnelImages[] {    firstImage,    secondImage,    names[] {      name,      description    }  }}
export type GetPersonnelImagesQueryResult = Array<{
  personnelImages: Array<{
    firstImage: CustomImage;
    secondImage: CustomImage;
    names: Array<{
      name: string;
      description: string;
    }> | null;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n*[_type == \"club\" && slug.current == $slug][0] {\n  title,\n  description,\n  partner->{\n    partnerImage\n  },\n  image,\n  _createdAt,\n  \"slug\": slug.current,\n  seo\n}\n": GetClubBySlugQueryResult;
    "\n*[_type == \"club\"] {\n  \"slug\": slug.current,\n}\n": GetClubSlugsQueryResult;
    "\n*[_type == \"club\"] | order(date desc) {\n  title,\n  shortDescription,\n  partner->{\n    partnerImage,\n    _id\n  },\n  image,\n  date,\n  \"slug\": slug.current,\n}\n": GetClubsQueryResult;
    "\n*[_type == \"partner\"] {\n  _id,\n  name\n}\n": GetClubsPartnersReferenceDataQueryResult | GetPartnersReferenceDataQueryResult;
    "\n*[_type == \"siteSettings\"]{\n  title,\n  siteUrl,\n  description,\n  keywords,\n  defaultOgImage,\n  organization,\n  socialMedia\n}\n": GetSiteSettingsQueryResult;
    "\n*[_type == \"galleryFolder\"] {\n  _id,\n  name,\n  \"slug\": slug.current,\n  coverImage,\n  \"latestImages\": images | order(_key desc) [0...3]\n}\n": GetGalleriesQueryResult;
    "\n*[_type == \"galleryFolder\" && slug.current == $slug][0] {\n  name,\n  \"slug\": slug.current,\n  coverImage,\n  images[],\n  seo\n}\n": GetGalleryBySlugQueryResult;
    "\n*[_type == \"examplePage\"]\n{\ntitle,\nsections,\nseo\n}\n": GetHomeSectionsQueryResult;
    "\n*[_type == \"post\"] | order(date desc)[0...3] {\n  _id,\n  title,\n  shortDescription,\n  image,\n  date,\n  \"slug\": slug.current,\n  partner->{\n    name,\n    partnerImage\n  }\n}\n": GetLastThreeProjectsQueryResult;
    "\n*[_type == \"partner\"] {\n  partnerImage\n}\n": GetPartnersQueryResult;
    "\n*[_type == \"post\" && slug.current == $slug][0] {\n  title,\n  description,\n  image,\n  partner->{\n    partnerImage\n  },\n  _createdAt,\n  \"slug\": slug.current,\n  seo\n}\n": GetProjectQueryResult;
    "\n*[_type == \"post\"] {\n  \"slug\": slug.current,\n}\n": GetProjectSlugsQueryResult;
    "\n*[_type == \"post\"] | order(date desc) {\n  title,\n  shortDescription,\n  image,\n  partner->{\n    partnerImage,\n    _id\n  },\n  date,\n  \"slug\": slug.current,\n}\n": GetProjectsQueryResult;
    "\n*[_type == \"structureSchoolPage\"] {\n  filesToDownload[] {\n    fileName,\n    \"downloadUrl\": asset->url\n  }\n}\n": GetFilesToDownloadQueryResult;
    "\n*[_type == \"structureSchoolPage\"] {\n  personnelImages[] {\n    firstImage,\n    secondImage,\n    names[] {\n      name,\n      description\n    }\n  }\n}\n": GetPersonnelImagesQueryResult;
  }
}
